name: av_spanish_admin
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  bloc_concurrency: ^0.2.2
  build_runner: ^2.3.3
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  json_serializable: ^6.6.1
  provider: ^6.0.5
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

 